"""empty message

Revision ID: 40f81c8cd8cb
Revises: 
Create Date: 2024-11-12 15:45:10.680046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f81c8cd8cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('make',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'PAID', 'NOT_PAID', name='userstatus'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lot_number', sa.BigInteger(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('highlight_id', sa.Integer(), nullable=True),
    sa.Column('primary_damage_id', sa.Integer(), nullable=True),
    sa.Column('secondary_damage_id', sa.Integer(), nullable=True),
    sa.Column('body_id', sa.Integer(), nullable=True),
    sa.Column('motor_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('drive_id', sa.Integer(), nullable=True),
    sa.Column('fuel_id', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.SmallInteger(), nullable=True),
    sa.Column('trim_level', sa.String(length=50), nullable=True),
    sa.Column('vin_code', sa.String(), nullable=True),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('estimated_retail_value', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('has_keys', sa.String(length=10), nullable=True),
    sa.Column('buy_it_now_price', sa.Float(), nullable=True),
    sa.Column('buy_it_now_flag', sa.Boolean(), nullable=False),
    sa.Column('seller_reserve_met', sa.Float(), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('lot_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drive_id'], ['drive.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_damage_id'], ['damage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secondary_damage_id'], ['damage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_data_lot_number'), 'main_data', ['lot_number'], unique=False)
    op.create_table('user_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('highlight_id', sa.Integer(), nullable=True),
    sa.Column('primary_damage_id', sa.Integer(), nullable=True),
    sa.Column('secondary_damage_id', sa.Integer(), nullable=True),
    sa.Column('body_id', sa.Integer(), nullable=True),
    sa.Column('motor_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('drive_id', sa.Integer(), nullable=True),
    sa.Column('fuel_id', sa.Integer(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('odometer_min', sa.Float(), nullable=True),
    sa.Column('odometer_max', sa.Float(), nullable=True),
    sa.Column('release_date_min', sa.Integer(), nullable=False),
    sa.Column('release_date_max', sa.Integer(), nullable=False),
    sa.Column('has_keys', sa.String(length=10), nullable=False),
    sa.Column('buy_it_now_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drive_id'], ['drive.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_damage_id'], ['damage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secondary_damage_id'], ['damage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_filters')
    op.drop_index(op.f('ix_main_data_lot_number'), table_name='main_data')
    op.drop_table('main_data')
    op.drop_table('model')
    op.drop_table('users')
    op.drop_table('transmission')
    op.drop_table('motor')
    op.drop_table('make')
    op.drop_table('highlights')
    op.drop_table('fuel')
    op.drop_table('drive')
    op.drop_table('damage')
    op.drop_table('body')
    # ### end Alembic commands ###
