"""empty message

Revision ID: 7054bb931140
Revises: 40f81c8cd8cb
Create Date: 2024-11-12 15:49:28.574701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7054bb931140'
down_revision: Union[str, None] = '40f81c8cd8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motor', sa.Column('tittle', sa.String(), nullable=False))
    op.drop_column('motor', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motor', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('motor', 'tittle')
    # ### end Alembic commands ###
