"""empty message

Revision ID: eebca0650141
Revises: e75f3df5bb2c
Create Date: 2024-11-13 16:27:55.726687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebca0650141'
down_revision: Union[str, None] = 'e75f3df5bb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'deleted_entries',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('logs', 'added_entries',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('logs', 'updated_entries',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'updated_entries',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logs', 'added_entries',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logs', 'deleted_entries',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
